_wandb:
    value:
        cli_version: 0.22.3
        e:
            yl88ba0caujj2kbp1g0mfojxdxq6d4w4:
                args:
                    - --index
                    - "3"
                    - --kfold
                    - "0"
                    - --model
                    - btc
                    - --dataset1
                    - billboard
                    - --dataset2
                    - jaah
                    - --test_dataset
                    - rwc
                    - --restore_epoch
                    - "1000"
                    - --dataset3
                    - dj_avan
                    - --voca
                    - --early_stop
                codePath: BTC-ISMIR19/train_curriculum.py
                codePathLocal: train_curriculum.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "2081087713280"
                        used: "211864608768"
                email: biabcaval@gmail.com
                executable: /home/daniel.melo/miniconda3/envs/BTC_py310/bin/python
                git:
                    commit: 0d89393da8c757fb9d25ce0b4e89e1d1778b5507
                    remote: https://github.com/biabcaval/chords_recog.git
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-fd6dfa07-ec6b-bf79-da2b-96d38fd9affa
                host: daniel-chords-machine
                memory:
                    total: "33649217536"
                os: Linux-6.8.0-1043-gcp-x86_64-with-glibc2.35
                program: /home/daniel.melo/BTC_ORIGINAL/chords_recog/BTC-ISMIR19/train_curriculum.py
                python: CPython 3.10.19
                root: /home/daniel.melo/BTC_ORIGINAL/chords_recog/BTC-ISMIR19
                startedAt: "2025-11-29T06:53:22.242545Z"
                writerId: yl88ba0caujj2kbp1g0mfojxdxq6d4w4
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 53
            "2":
                - 1
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
            "4": 3.10.19
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
batch_size:
    value: 128
curriculum:
    value: false
curriculum_pace_epochs:
    value: 30
curriculum_pacing:
    value: linear
curriculum_start_ratio:
    value: 0.3
curriculum_strategy:
    value: mixed
dataset1:
    value: billboard
dataset2:
    value: jaah
dataset3:
    value: dj_avan
early_stop:
    value: true
experiment_index:
    value: 3
kfold:
    value: 0
large_voca:
    value: true
learning_rate:
    value: 0.0001
max_epoch:
    value: 100
model:
    value: btc
num_chords:
    value: 170
restore_epoch:
    value: 1000
test_dataset:
    value: rwc
voca:
    value: true
