_wandb:
    value:
        cli_version: 0.22.3
        e:
            14y1n47cizkfgggyn03r7ibzszxpzdup:
                args:
                    - --index
                    - "6"
                    - --kfold
                    - "0"
                    - --model
                    - btc
                    - --dataset1
                    - jaah
                    - --dataset2
                    - dj_avan
                    - --dataset3
                    - robbiewilliams
                    - --dataset4
                    - queen
                    - --dataset5
                    - billboard
                    - --test_dataset
                    - rwc
                    - --voca
                    - --early_stop
                codePath: BTC-ISMIR19/train_curriculum.py
                codePathLocal: train_curriculum.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "2081087713280"
                        used: "227074985984"
                email: biabcaval@gmail.com
                executable: /home/daniel.melo/miniconda3/envs/BTC_py310/bin/python
                git:
                    commit: 6d8efe0ca48f589c164b3a11f5119ab49a402768
                    remote: https://github.com/biabcaval/chords_recog.git
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-282746d5-882b-d973-2d4c-eafe6247bdf3
                host: daniel-chords-machine
                memory:
                    total: "33649225728"
                os: Linux-6.8.0-1044-gcp-x86_64-with-glibc2.35
                program: /home/daniel.melo/BTC_ORIGINAL/chords_recog/BTC-ISMIR19/train_curriculum.py
                python: CPython 3.10.19
                root: /home/daniel.melo/BTC_ORIGINAL/chords_recog/BTC-ISMIR19
                startedAt: "2025-12-10T15:02:26.125684Z"
                writerId: 14y1n47cizkfgggyn03r7ibzszxpzdup
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 53
            "2":
                - 1
                - 2
                - 3
                - 5
                - 53
            "3":
                - 13
                - 15
                - 16
            "4": 3.10.19
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
batch_size:
    value: 128
class_weights_enabled:
    value: true
class_weights_gamma:
    value: 0.5
class_weights_w_max:
    value: 10
curriculum:
    value: false
curriculum_pace_epochs:
    value: 30
curriculum_pacing:
    value: linear
curriculum_start_ratio:
    value: 0.3
curriculum_strategy:
    value: mixed
dataset1:
    value: jaah
dataset2:
    value: dj_avan
dataset3:
    value: robbiewilliams
dataset4:
    value: queen
dataset5:
    value: billboard
early_stop:
    value: true
experiment_index:
    value: 6
kfold:
    value: 0
large_voca:
    value: true
learning_rate:
    value: 0.0001
max_epoch:
    value: 100
model:
    value: btc
num_chords:
    value: 170
restore_epoch:
    value: 1000
test_dataset:
    value: rwc
voca:
    value: true
